Fix AtariPreprocessing gym wrapper
tensorflow/agents pull request #171
Opened 2019-07-24 11:28 UTC by seungjaeryanlee

This PR suggests saving unwrapped environment as a parameter to call `reset()` and `step()`.

Fixes #170  , and the warning no longer appears.

2019-07-25 23:03 UTC, sguada approved these changes

2019-07-30 20:33 UTC, samfishman requested changes
Please use the already-present `self.env` rather than `self._env`.

2019-07-30 20:33 UTC, samfishman commented on tf_agents/environments/atari_preprocessing.py
> +    self._env = env
This is unnecessary - the call to `super.__init__` saves the env as `self.env`.

2019-07-30 20:33 UTC, samfishman commented on tf_agents/environments/atari_preprocessing.py
> +    self._env.reset()
`self.env`

2019-07-30 20:33 UTC, samfishman commented on tf_agents/environments/atari_preprocessing.py
> +      _, reward, game_over, info = self._env.step(action)
`self.env`

2019-08-03 20:04 UTC, seungjaeryanlee commented
[Did not notice this!](https://github.com/openai/gym/blob/5e6f11d07781404459672e114cb86cb6a1a015c6/gym/core.py#L207) Thank you for your review @samfishman

2020-03-26 00:52 UTC, tfboyd commented
Person is using self.env, if the tests pass I will +2 and ask for internal review and finally get this merged.

2020-03-26 18:36 UTC, merged