Peter zhizhin train in non episodic
tensorflow/agents pull request #306
Opened 2020-02-11 23:53 UTC by tfboyd

I just merged Peter Zhinzhin's changes and fixed the conflicts.  There is no attempt to take any credit. Peter's commits are in this PR with my final commit doing the merge conflict.  

Getting ready to run unit tests, will update this commit when done.

2020-02-11 23:54 UTC, tfboyd commented
Marking CLA yes as Peter as signed it in the other PR and this is me merging everything.  This is on the up and up.

2020-02-11 23:55 UTC, tfboyd commented
Trying my kokoro unit tests.  :-)

2020-02-11 23:58 UTC, tfboyd commented
@PeterZhizhin  Just heads up I made a new PR with your commits.

2020-02-12 00:06 UTC, sguada requested changes

2020-02-12 00:06 UTC, sguada commented on tf_agents/agents/ppo/ppo_utils.py
> +  if episode_is_complete is None:
```
mask = not_between_episodes
if allow_partial_episodes:
  mask = mask & episode_is_complete
return tf.cast(mask, tf.float32)
```

2020-02-12 00:06 UTC, sguada commented on tf_agents/agents/ppo/ppo_utils.py
> +  else:
`if not allow_partial_episodes:`

2020-02-12 04:53 UTC, ebrevdo commented on tf_agents/agents/ppo/ppo_agent.py
> +      train_on_partial_episodes: If True (default False), then data from
let's remove this arg and assume it's always True; per oscar's comment on original PR.

2020-02-12 19:00 UTC, tfboyd commented
@kuanghuei

2020-02-18 19:27 UTC, merged