Add support for RandomPyPolicy parameters in validate_py_environment
tensorflow/agents pull request #586
Opened 2021-04-07 01:02 UTC by AbhijeetKrishnan

#584 

Adds an extra parameter to `validate_py_environment`, namely `observation_and_action_constraint_splitter`. This would be useful for environments where randomly sampling the action space produces more invalid actions than valid actions. In such environments, passing an `observation_and_action_constraint_splitter` would make the RandomPyPolicy select only valid actions, potentially making the validation process more thorough.

I have not added any tests to `utils_test.py` and would like help on what some meaningful tests would be.

2021-04-07 10:14 UTC, sguada requested changes

2021-04-07 10:14 UTC, sguada commented on tf_agents/environments/utils.py
> +      time_step_spec=time_step_spec,
Remove extra space at the end of the line

2021-04-07 10:14 UTC, sguada commented on tf_agents/environments/utils.py
> +        observation_and_action_constraint_splitter))
indent another 2 spaces.

2021-04-18 04:43 UTC, AbhijeetKrishnan commented
Any follow-up to this?

2021-04-19 14:49 UTC, kbanoop approved these changes

2021-04-19 16:55 UTC, kbanoop commented
Thank you. Can you please resolve the conflict? After that I can import it into the internal review system

2021-04-19 18:32 UTC, AbhijeetKrishnan commented
Fixed the issue regarding a missing newline at the end of the .gitignore file.

2021-04-21 00:04 UTC, merged