Bias Layer: Add support for regularizer and constraint
tensorflow/agents pull request #731
Opened 2022-04-05 12:05 UTC by saisua

Small patch to add the bias_regularizer and bias_constraint. It is needed to be like other layers in TF2.0.
They are initialized as None based on current master.

2022-04-05 12:12 UTC, sguada commented on tf_agents/keras_layers/bias_layer.py
> +  def __init__(self, bias_initializer='zeros', bias_regularizer=None, bias_constraint=None, **kwargs):
Can you reformat so it doesn't go over 80 characters and each argument use one line. Ex:
def __init__(self, 
                     bias_initializer='zeros',
                     bias_regularizer=None,
                     bias_constraint=None, 
                     **kwargs):

2022-04-05 12:25 UTC, saisua commented
I just did that. Thank you for your quick response.
As a side note, I have seen that there is a file called something like "bias layer test". I have not touched it but feel free to ask for anything.

2022-04-05 12:55 UTC, sguada commented
Please add 2 new test to make sure the new arguments work as expected.

2022-04-06 11:00 UTC, sguada requested changes
Add tests for the new parameters.

2023-09-30 13:13 UTC, tfboyd commented
This has been about 1.5 years. I am making this closed.  We can always reopen.  I am merging PRs where with my knowledge can get the merged. This one is too big for me to handle unfortunately. Sometimes things rot on the vine; sad and a reality. 

Thank you for the effort and sorry this did not make it to the finish.

2023-09-30 13:13 UTC, closed without merging