Updated PyDriver Constructor to be more readable.
tensorflow/agents pull request #74
Opened 2019-04-11 01:12 UTC by idigitopia

Resolves Issue #67 

```
import numpy as np
import itertools

# Very Confusing
def old_func(max_steps, max_episodes):
	max_steps = max_steps or 0
	max_episodes = max_episodes or 0

	if max_steps < 1 and max_episodes < 1:
		return 'Error'

	_max_steps = max_steps or np.inf
	_max_episodes = max_episodes or np.inf
	return (_max_steps, _max_episodes)

# More Readable
def new_func(max_steps, max_episodes):
	if max_steps in (None, 0) and max_episodes in (None, 0):
		return 'Error'

	_max_steps = max_steps or np.inf
	_max_episodes = max_episodes or np.inf
	return (_max_steps, _max_episodes)

test_cases = [i for i in itertools.product([None, 0, 4], repeat=2)]

for case in test_cases:
	assert old_func(*case) == new_func(*case)
```

2019-04-11 01:13 UTC, idigitopia commented
I signed it!

2019-05-14 21:29 UTC, sguada requested changes

2019-05-14 21:29 UTC, sguada commented on tf_agents/drivers/py_driver.py
> +    if max_steps in (None, 0) and max_episodes in (None, 0):
This doesn't test that max_steps or max_episodes is not negative.

2020-02-05 22:03 UTC, tfboyd commented
Last activity was May 2019.  A lot of time has passed, closing the issue due to lack of activity.

2020-02-05 22:03 UTC, closed without merging